### ISSUE TITLE
Web server not loading

### ISSUE THREAD

**Issue by rw377** [mmcc-xx/WhosAtMyFeeder#22]
**EDIT: Just noticed that 7767 is the default webui port on config.yml but 7766 is listed on docker-compose. Changed config.yml to 7766 and it's not good to go** 
----------
I'm running Frigate on Home Assistant and have exposed port 5000 per the instructions. I have confirmed I can access Frigate via URL:5000. The container seems to run fine but I am not getting anything when I go to the URL (localhost or from LAN).  Is there anything I can do to see whats going on here? Not sure where the problem is. 

-Docker compose is a direct copy from Git
-Config has been changed w/ proper information for Frigate + MQQT added to the config
-Folder configuration looks good per the directions

docker ps
![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/75325891/f75ec410-dc92-46db-af84-de457f7f5f9e)
netstat -lnpt | grep 7766:
![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/75325891/b84c0ed2-2962-4e8a-aacd-0c33461dbf9a)

Docker config:
![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/75325891/0b9429f5-4ae2-4d7c-bd1e-5385ff2dc77a)
docker-compose.yml:
![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/75325891/0c9980f3-d450-4ffa-81ac-a405a2980d65)
ls -R whosatmyfeeder/:
![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/75325891/2bd1b1fd-41f7-4f0e-a933-18f6c08d55d0)
As far as I can tell things look fine if I exec into the container:
![image](https://github.com/mmcc-xx/WhosAtMyFeeder/assets/75325891/bdeb9f05-942f-4ea1-9071-740d71e6486a)

**Comment by mmcc-xx** [comment]
Well that must have been annoying. I'm changing the default in the config file to 7766 as I can't imagine a reason for having it the other way.
